<!DOCTYPE html>
<!--nobanner-->
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
<title>パスワード設定</title>
<link rel="stylesheet" href="css/ress.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/sp-menu.css" type="text/css" />
<link rel="stylesheet" href="css/toastr.min.css" type="text/css" />
<script type="text/javascript" src="js/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="js/toastr.min.js"></script>
<style>
.content {
  margin: 20px 0px;
  width: 100%;
  text-align: center;
}
  select {
  appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  -webkit-appearance: none;
  background: url(/image/material_arrow_blue02.png) no-repeat;
  background-position: 90% center;
  border: 1px solid #D7D7D7;
  box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  cursor: pointer;
  text-indent: 15px;
  text-overflow: "";
  padding: 5px;
  height: 40px;
  width: 80%;
}
input[type=password] {
  background: #fff;
  border: 1px solid #D7D7D7;
  box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  border-radius: 3px;
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  padding: 5px;
  height: 40px;
  width: 80%;
}
p {
  background-color: #eee;
  margin: 10px;
  padding: 5px;
  border: solid 1px #ccc;
  width: 95%;
}
</style>
</head>
<body>
  <h1>パスワード設定</h1>
  <?= $this->fetch('menu.phtml', ['me' => $me]) ?>

  <p>
  ・利用者のパスワードを強制的に変更します。
  </p>

  <form class="content" method="POST" action="/chpassword">
    利用者<br>
  <select name="member">
    <option value=""></option>
    <? foreach($members as $id => $member) { ?>
    <option value="<?= e($id) ?>" <?= $id == $member_id ? 'selected' : '' ?>><?= e($member['name']) ?></option>
    <? } ?>
  </select>
  <br>
  <br>
  パスワード<br>
    <input type="password" name="pass" required />
    <br>
    <br>
    <input type="submit" value="更新" />
  </form>
  <script>
    toastr.options = {
      "positionClass": "toast-top-full-width",
      "timeOut": "2000",
    };
    $(function() {
      <? if (isset($info)) { ?>
        toastr.info('<?= e($info) ?>');
      <? } else if (isset($error)) { ?>
        toastr.error('<?= e($error) ?>');
      <? } ?>
    });
  </script>
</body>
</html>