<!DOCTYPE html>
<!--nobanner-->
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
<title>日付設定</title>
<link rel="stylesheet" href="css/ress.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/sp-menu.css" type="text/css" />
<script type="text/javascript" src="js/jquery-1.12.0.min.js"></script>
<style>
  .schedule {
    width: 98%;
    margin: 10px 5px 20px 5px;
  }
  .schedule td {
    padding: 5px;
  }
  input[type=text] {
    background: #fff;
    border: 1px solid #D7D7D7;
    box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
    -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
    -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
    -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
    -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
    border-radius: 3px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    padding: 5px;
    height: 40px;
    width: 95%;
  }
  ::placeholder {
    color: #ccc;
  }

  p {
    background-color: #eee;
    margin: 10px;
    padding: 5px;
    border: solid 1px #ccc;
    width: 95%;
  }
</style>
</head>
<body>
  <h1>日付設定</h1>
  <?= $this->fetch('menu.phtml', ['me' => $me]) ?>

  <p>
・日付の期間は自動で更新されます。
  </p>

  <form method="POST" action="/date">
  <table class="schedule">
    <? foreach($scheduleDates as $date => $content) { ?>
    <tr>
      <td style="text-align:right;"><?= dfmt($date) ?></td>
      <td style="width: 90%;"><input type="text" name = "comment[]" value="<?= e($content['comment']); ?>" placeholder="コメントを入力"><input type="hidden" name="date[]" value="<?= e($date); ?>"></td>
    </tr>
    <? } ?>
  </table>
  <input type="submit" value="更新" />
  </form>
</body>
</html>