<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
<title>メンバー設定</title>
<link rel="stylesheet" href="css/ress.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/style-add.css" type="text/css" />
<link rel="stylesheet" href="css/sp-menu.css" type="text/css" />
<link rel="stylesheet" href="css/jquery-ui-1.12.0.css" type="text/css" />
<link rel="stylesheet" href="css/toastr.min.css" type="text/css" />
<script type="text/javascript" src="js/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.12.0.min.js"></script>
<script type="text/javascript" src="js/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="js/toastr.min.js"></script>
<style>
.items {
  margin: 10px 60px 0px 10px;
  padding: 0px 5px;
}
.item {
  border-top: 2px solid rgba(0, 0, 0, 0.1);
  border-left: 2px solid rgba(0, 0, 0, 0.1);
  border-right: 4px solid rgba(0, 0, 0, 0.1);
  border-bottom: 4px solid rgba(0, 0, 0, 0.1);
  line-height: 40px;
  padding: 5px 20px 5px 20px;
  margin: 5px;
  background-color: white;
}
.add {
  margin: 0px 60px 20px 10px;
  padding: 0px 5px;
  text-align: center;
}
.additem {
  border-top: 2px solid rgba(0, 0, 0, 0.1);
  border-left: 2px solid rgba(0, 0, 0, 0.1);
  border-right: 4px solid rgba(0, 0, 0, 0.1);
  border-bottom: 4px solid rgba(0, 0, 0, 0.1);
  line-height: 40px;
  padding: 5px 20px 5px 20px;
  margin: 5px;
  background-color: lightblue;
}
.removeitem {
  background-color: lightgray;
}

.modal-text {
  background: #fff;
  border: 1px solid #D7D7D7;
  box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  border-radius: 3px;
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  padding: 5px;
  height: 40px;
  width: 100%;
}
.list-text {
  border: none;
  width: 60%;
  padding: 5px;
  height: 40px;
}

input[type=checkbox] {
    display: none;
}
.checkbox01 {
    box-sizing: border-box;
    /*cursor: pointer;*/
    display: inline-block;
    padding: 5px 30px;
    position: relative;
    width: auto;
}
.checkbox01::before {
    background: #fff;
    border: 1px solid #231815;
    border-radius: 3px;
    content: '';
    display: block;
    height: 16px;
    left: 5px;
    margin-top: -8px;
    position: absolute;
    top: 50%;
    width: 16px;
}
.checkbox01::after {
    border-right: 3px solid royalblue;
    border-bottom: 3px solid royalblue;
    content: '';
    display: block;
    height: 12px;
    left: 9px;
    margin-top: -7px;
    opacity: 0;
    position: absolute;
    top: 50%;
    transform: rotate(45deg);
    width: 8px;
}
input[type=checkbox]:checked + .checkbox01::after {
    opacity: 1;
}

.content{
    margin: 0 auto;
    padding: 20px;
  }
  .modal{
    display: none;
    height: 100vh;
    position: fixed;
    top: 0;
    width: 100%;
	  z-index: 900;
  }
  .modal__bg{
    background: rgba(0,0,0,0.8);
    height: 100vh;
    position: absolute;
    width: 100%;
	  z-index: 901;
  }
  .modal__content{
    background: #fff;
    left: 50%;
    padding: 20px;
    position: absolute;
    top: 50%;
    transform: translate(-50%,-50%);
    width: 60%;
    text-align: center;
	  z-index: 902;
  }

  .cancel {
    background-color: dimgray;
  }

  .modal-form{
    text-align: left;
    padding: 5px 0px;
  }

  p {
    background-color: #eee;
    margin: 10px;
    padding: 5px;
    border: solid 1px #ccc;
    width: 95%;
  }

  .draggable {
    margin-top: 5px;
    height: 20px;
    width: 6px;
    display: inline-block;
    box-sizing: border-box;
    float: right;
    line-height: 0.4em;
  }
  .draggable div {
    right: 0;
    height: 3px;
    width: 5px;
    background-color: #ccc;
    border-radius: 2px;
    display: inline-block;
    box-sizing: border-box;
  }
</style>
</head>
<body>
  <div class="title-bar">
    <h1>メンバー設定</h1>
    <?= $this->fetch('menu.phtml', ['me' => $me]) ?>
  </div>

  <p>
・タップして編集します。<br>
・ドラッグで並び替えます。<br>
・「更新を確定」で更新が反映されます。<br>
・新しく追加した利用者はパスワードがありません。「パスワード設定」メニューよりパスワードを設定してください。
  </p>

  <div id="modal" class="modal js-modal">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <div class="modal-form"><input type="text" class='modal-text' id='modal-name' name="modal-name" value="" placeholder="名前を入力" /></div>
      <div class="modal-form"><input type="checkbox" id='modal-is_admin' name="modal-is_admin" /><label for="modal-is_admin" class="checkbox01">管理者に設定</label></div>
      <div class="modal-form"><input type="checkbox" id="modal-remove" name="modal-remove" /><label for="modal-remove" class="checkbox01">利用者を削除</label></div>
      <input type="hidden" name="modal-member_id" value="0" />
      <br>
      <a class="js-modal-close" href="" name="update"><div class="button">更新</div></a>
      <a class="js-modal-close" href="" name="cancel"><div class="button cancel">キャンセル</div></a>
    </div>
  </div>

  <div id="add-modal" class="modal js-modal">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">
      <div class="modal-form"><input type="text" class='modal-text' id='add-modal-name' name="add-modal-name" value="" placeholder="名前を入力" /></div>
      <div class="modal-form"><input type="checkbox" id='add-modal-is_admin' name="add-modal-is_admin" /><label for="add-modal-is_admin" class="checkbox01">管理者に設定</label></div>
      <br>
      <a class="js-modal-close" href="" name="add"><div class="button">追加</div></a>
      <a class="js-modal-close" href="" name="cancel"><div class="button cancel">キャンセル</div></a>
    </div>
  </div>

  <form method="POST" action="/member">
  <div class='items'>
    <div class='item js-modal-open' data-target='modal' id='copy-item' style='display: none;'>
      <input type='text' class='list-text' name='name[]' value='' readonly>
      <label></label>
      <input type="hidden" name="remove[]" value='0'>
      <input type="hidden" name="is_admin[]" value='0'>
      <input type="hidden" name="member_id[]" value='' />
      <div class="draggable"><div></div><div></div><div></div></div>
    </div>
    <? foreach($members as $member_id => $member) { ?>
    <div class='item js-modal-open' id="upd-<?= $member_id ?>" data-target='modal'>
      <input type='text' class='list-text' name='name[]' value='<?= e($member['name']); ?>' readonly>
      <label><?= $member['is_admin'] ? '(管)' : '' ?></label>
      <input type="hidden" name="is_admin[]" value='<?= $member['is_admin'] ? '1' : '0' ?>'>
      <input type="hidden" name="remove[]" value='0'>
      <input type="hidden" name="member_id[]" value='<?= $member_id ?>' />
      <div class="draggable"><div></div><div></div><div></div></div>
    </div>
    <? } ?>
  </div>
  <div class="add">
    <div class='js-modal-open additem' data-target='add-modal'>追加</div>
    </div>
  <input type="submit" value="更新を確定" />
  </form>
  <script>
    toastr.options = {
      "positionClass": "toast-top-full-width",
      "timeOut": "2000",
    };
    $(function() {
      <? if (isset($info)) { ?>
        toastr.info('<?= e($info) ?>');
      <? } else if (isset($error)) { ?>
        toastr.error('<?= e($error) ?>');
      <? } ?>

      $( ".items" ).sortable({
        axis: 'y',
      });

      $('.js-modal-open').each(function(){
        $(this).on('click',function(){
          $('input[name="modal-name"]').val($(this).find('input[name="name[]"]').val());
          if ($(this).find('input[name="is_admin[]"]').val() == '1') {
            $('input[name="modal-is_admin"]').prop('checked', true);
          } else {
            $('input[name="modal-is_admin"]').prop('checked', false);
          }
          if ($(this).find('input[name="remove[]"]').val() == '1') {
            $('input[name="modal-remove"]').prop('checked', true);
          } else {
            $('input[name="modal-remove"]').prop('checked', false);
          }
          $('input[name="modal-member_id"]').val($(this).prop('id'));

          var target = $(this).data('target');
          var modal = document.getElementById(target);
          $(modal).fadeIn();
          return false;
        });
      });

      $('.js-modal-close').on('click',function(){
          if ($(this).prop('name') == 'add') {
            var name = $('#add-modal-name').val();
            if (name == '') {
              toastr.error("名前を入力してください");
              return false;
            }
            var is_admin = $('#add-modal-is_admin').prop('checked') ? '1' : '0';
            var uid = Date.now().toString(16);
            var newItem = $('#copy-item').clone(true);
            newItem.prop('id', 'add-' + uid);
            newItem.find('input[name="name[]"]').val(name);
            newItem.find('input[name="is_admin[]"]').val(is_admin);
            if (is_admin == '1') {
              newItem.find('label').text('(管)');
            } else {
              newItem.find('label').text('');
            }
            newItem.find('input[name="member_id[]"]').val('add-' + uid);
            $('.items').append(newItem);
            newItem.css('display', 'block');
          } else if ($(this).prop('name') == 'update') {
            var name = $('#modal-name').val();
            if (name == '') {
              toastr.error("名前を入力してください");
              return false;
            }
            var is_admin = $('#modal-is_admin').prop('checked') ? '1' : '0';
            var selector = '#' + $('input[name="modal-member_id"]').val();
            $(selector).find('input[name="name[]"]').val(name);
            $(selector).find('input[name="is_admin[]"]').val(is_admin);
            if (is_admin == '1') {
              $(selector).find('label').text('(管)');
            } else {
              $(selector).find('label').text('');
            }
            var remove = $('#modal-remove').prop('checked') ? '1' : '0';
            $(selector).find('input[name="remove[]"]').val(remove);
            if (remove == '1') {
              $(selector).css('background-color', 'lightgray');
            } else {
              $(selector).css('background-color', 'white');
            }
          }

        $('.js-modal').fadeOut();
        return false;
      }); 
    });
  </script>
</body>
</html>