<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
<title>パスワード変更</title>
<link rel="stylesheet" href="css/ress.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/style-add.css" type="text/css" />
<link rel="stylesheet" href="css/sp-menu.css" type="text/css" />
<link rel="stylesheet" href="css/toastr.min.css" type="text/css" />
<script type="text/javascript" src="js/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="js/toastr.min.js"></script>
<style>
.content {
  width: 100%;
  text-align: center;
}
input[type=password] {
  background: #fff;
  border: 1px solid #D7D7D7;
  box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  border-radius: 3px;
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  padding: 5px;
  height: 40px;
  width: 80%;
}
</style>
</head>
<body>
  <div class="title-bar">
    <h1>パスワード変更</h1>
    <?= $this->fetch('menu.phtml', ['me' => $me]) ?>
  </div>

  <h2><?= e($me['name']); ?></h2>

  <form class="content" method="POST" action="/password">
    新しいパスワードを入力してください
    <input type="password" name="pass" required />
    <br>
    <br>
    <input type="submit" value="変更" />
  </form>
  <script>
    toastr.options = {
      "positionClass": "toast-top-full-width",
      "timeOut": "2000",
    };
    $(function() {
      <? if (isset($info)) { ?>
        toastr.info('<?= e($info) ?>');
      <? } else if (isset($error)) { ?>
        toastr.error('<?= e($error) ?>');
      <? } ?>
    });
  </script>
</body>
</html>