<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
<title>予定入力</title>
<link rel="stylesheet" href="css/ress.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/style-add.css" type="text/css" />
<link rel="stylesheet" href="css/sp-menu.css" type="text/css" />
<script type="text/javascript" src="js/jquery-1.12.0.min.js"></script>
<style>
  .schedule {
    width: 98%;
    margin: 10px 5px 20px 5px;
  }
  .schedule td {
    padding: 5px;
  }
  select {
  appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  -webkit-appearance: none;
  background: url(/image/material_arrow_blue02.png) no-repeat;
  background-position: 92% center;
  border: 1px solid #D7D7D7;
  box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  cursor: pointer;
  text-indent: 0px;
  text-overflow: "";
  padding: 5px;
  height: 40px;
  width: 100%;
}
input[type=text] {
  background: #fff;
  border: 1px solid #D7D7D7;
  box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -o-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -ms-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -moz-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: 0px 1px 2px rgba(0,0,0,0.1);
  border-radius: 3px;
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  padding: 5px;
  height: 40px;
  width: 100%;
}
::placeholder {
  color: #ccc;
}
</style>
</head>
<body>
  <div class="title-bar">
    <h1>予定入力</h1>
    <?= $this->fetch('menu.phtml', ['me' => $me]) ?>
  </div>

  <h2><?= e($me['name']); ?></h2>

  <form method="POST" action="/schedule">
  <table class="schedule">
    <? foreach($scheduleDates as $date => $content) { ?>
    <tr>
      <td style="white-space: norwap; text-align:right;"><?= dfmt($date) ?></td>
      <td style="width: 40%;">
        <select name="schedule_type_id[]">
          <option value="0"></option>
          <? foreach($scheduleTypes as $id => $type) { ?>
          <option value="<?= e($id) ?>" <?= $schedules[$date]['schedule_type_id'] == $id ? 'selected' : ''?>><?= e($type['symbol'].' ('.$type['description'].')'); ?></option>
          <? } ?>
        </select>
      </td>
      <td style="width=40%"><input type="text" name = "comment[]" value="<?= e($schedules[$date]['comment']); ?>" placeholder="コメントを入力"><input type="hidden" name="date[]" value="<?= e($date); ?>"></td>
    </tr>
    <? } ?>
  </table>
  <input type="submit" value="更新" />
  </form>
</body>
</html>